<a href="https://colab.research.google.com/github/kaushal4445/NUMPY-PRACTICE/blob/main/day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Creating array from Scratch**

In [3]:
import numpy as np
zeros  = np.zeros((3,4))
print("zeroes array : \n" , zeros)

zeroes array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
ones  = np.ones((2,3))
print("ones array : \n" , ones)

ones array : 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
full = np.full((2, 2) , 7)
print("full array : \n" , full)

full array : 
 [[7 7]
 [7 7]]


# **Random**

In [7]:
random = np.random.rand(2,3)
print(" random array : \n", random)

 random array : 
 [[0.53393697 0.47215428 0.6448752 ]
 [0.67665965 0.4859766  0.05421979]]


In [9]:
sequence = np.arange(0, 10, 2)
print("sequence array :\n", sequence)

sequence array :
 [0 2 4 6 8]
